In [ ]:
import tensorflow as tf
import numpy as np
from PIL import Image
from keras.models import Model
import pandas as pd

In [ ]:
# Mount Google Drive
from google.colab import drive
drive.mount('/content/Drive', force_remount=True)
# When you run this block, you will need to click open a link to get some 
import os
#TODO
os.chdir('/content/Drive/My Drive/DataMining_Project_Mine/')
model = tf.keras.models.load_model('basic_cnn_checkpoint_4_dropout0.15_l2_reg')

Mounted at /content/Drive


In [ ]:
top_dir = 'data/raw'
os.chdir('/content/Drive/My Drive/DataMining_Project/' + top_dir)
intermediate_layer_model = Model(inputs=model.input, outputs=model.layers[-3].output)
numpys = []
labels = []

for root, dirs, files in os.walk(os.getcwd()):
    folder = root[root.rfind("/"):]
    for file in files:
        im = Image.open(root + "/" + file)
        imArr = np.array(im).reshape(1, 256, 256, 3)
        dense_output = intermediate_layer_model.predict(imArr)
        numpys.append(dense_output)
        labels.append(folder[1:])


In [ ]:
numpys = np.array(numpys).reshape((8567, 100))
df1 = pd.DataFrame(numpys)
df2 = pd.DataFrame(labels)

In [ ]:
df = pd.concat([df1, df2], axis =1)
df

In [ ]:
os.chdir('/content/Drive/My Drive/DataMining_Project/data/')
df.to_csv('basic_droput_and_reg.csv', ',', header=False, index=False)

In [ ]:
features = pd.read_csv('basic_droput_and_reg.csv', header=None)
labels = features[100]
features = features.drop(100, axis=1)
features

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

train_features, test_features, train_labels, test_labels = train_test_split(features, labels, test_size = 0.25, random_state = 42)
# Instantiate model with 1000 decision trees
rf = RandomForestClassifier(n_estimators = 1000, random_state = 42)
# Train the model on training data
rf.fit(train_features, train_labels);

In [ ]:
predictions = rf.predict(test_features)
corr = 0
tot = 0
for x in range(len(predictions)):
  if(predictions[x] == test_labels.iloc[x]):
    corr += 1
  tot += 1

print("accuracy: " + str(corr/tot))  



accuracy: 0.33426704014939307


In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(test_labels, predictions))
print(classification_report(test_labels,predictions))

In [ ]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='linear')
svclassifier.fit(train_features, train_labels)

SVC(kernel='linear')

In [ ]:
pred = svclassifier.predict(test_features)
corr = 0
tot = 0
for x in range(len(predictions)):
  if(pred[x] == test_labels.iloc[x]):
    corr += 1
  tot += 1

print("accuracy: " + str(corr/tot))  


accuracy: 0.35154061624649857


In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(test_labels, pred))
print(classification_report(test_labels,pred))

[[23  1  3 ...  0  1  0]
 [ 5  0  2 ...  0  0  0]
 [ 7  0 13 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 7  0  0 ...  0  0  5]
 [ 6  0  0 ...  0  1 34]]
                                                  precision    recall  f1-score   support

                                apple apple scab       0.10      0.33      0.16        69
                                 apple black rot       0.00      0.00      0.00        23
                          apple cedar apple rust       0.23      0.22      0.22        59
                                   apple healthy       0.20      0.08      0.12        12
                                  banana healthy       0.56      0.40      0.47       166
                                 banana segatoka       0.61      0.61      0.61       327
                              banana xamthomonas       0.46      0.71      0.56       398
                 cherry (including sour) healthy       0.20      0.10      0.13        20
          cherry (including sour)

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
